version: 0.0
os: linux
files:
  - source: src/
    destination: /home/ec2-user/sample/
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
    - location: scripts/httpd_start.sh
      timeout: 300
      runas: root
